# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: eu.gcr.io/census-eq-ci/go-launch-a-survey
  tag: latest
  pullPolicy: Always

surveyRunnerUrl: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: launcher
  tls:
    - secretName: tls-cert